# Example GitHub Actions workflow for cross-platform builds
# This would go in .github/workflows/cross-platform-build.yml

name: Cross-Platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux-x64
          - os: windows-latest
            platform: win-x64
          - os: macos-latest
            platform: osx-arm64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Build C# native library
      run: |
        cd Rust/hpd_rust_agent
        ./build-native.sh ${{ matrix.platform }}
      shell: bash
    
    - name: Build and test Rust library
      run: |
        cd Rust/hpd_rust_agent
        cargo test
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: native-lib-${{ matrix.platform }}
        path: |
          Rust/hpd_rust_agent/*.dll
          Rust/hpd_rust_agent/*.dylib
          Rust/hpd_rust_agent/*.so
