using System;

/// <summary>
/// Metadata about a plugin, used for scoping and organization.
/// Generated by the source generator for plugins marked with [PluginScope].
/// </summary>
public class PluginMetadata
{
    /// <summary>
    /// Plugin name (typically the class name).
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Description of plugin capabilities (from [PluginScope] attribute).
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Names of all functions in this plugin.
    /// </summary>
    public string[] FunctionNames { get; set; } = Array.Empty<string>();

    /// <summary>
    /// Total number of functions in this plugin.
    /// </summary>
    public int FunctionCount { get; set; }

    /// <summary>
    /// Whether this plugin has the [PluginScope] attribute.
    /// If true, the plugin should be scoped (container generated).
    /// If false, all functions are always visible.
    /// </summary>
    public bool HasScopeAttribute { get; set; }
}
