import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Evaluations Overview","description":"","frontmatter":{},"headers":[],"relativePath":"guides/evaluations/overview.md","filePath":"guides/evaluations/overview.md","lastUpdated":null}');
const _sfc_main = { name: "guides/evaluations/overview.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="evaluations-overview" tabindex="-1">Evaluations Overview <a class="header-anchor" href="#evaluations-overview" aria-label="Permalink to &quot;Evaluations Overview&quot;">​</a></h1><p>Use evaluations to keep agent behavior from drifting. Start with a small batch eval, add more cases as bugs appear, then use live evaluation and red-team runs when you want signals from real traffic or adversarial prompts.</p><h2 id="pick-a-workflow" tabindex="-1">Pick A Workflow <a class="header-anchor" href="#pick-a-workflow" aria-label="Permalink to &quot;Pick A Workflow&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Goal</th><th>Start here</th></tr></thead><tbody><tr><td>Catch regressions in CI</td><td><a href="./batch-evals">Batch Evals</a></td></tr><tr><td>Choose the right evaluator</td><td><a href="./evaluator-picker">Evaluator Picker</a></td></tr><tr><td>Move test cases out of code</td><td><a href="./datasets-and-reports">Datasets And Reports</a></td></tr><tr><td>Score real runs after users get a response</td><td><a href="./live-evaluation">Live Evaluation</a></td></tr><tr><td>Grade subjective quality or safety</td><td><a href="./llm-judges-and-safety">LLM Judges And Safety</a></td></tr><tr><td>Try adversarial prompts against an agent</td><td><a href="./red-team">Red Team</a></td></tr></tbody></table><p>Batch evals are the fastest first win. You can run one without provider credentials by giving the agent a fixed or fake <code>IChatClient</code>.</p><h2 id="smallest-shape" tabindex="-1">Smallest Shape <a class="header-anchor" href="#smallest-shape" aria-label="Permalink to &quot;Smallest Shape&quot;">​</a></h2><div class="language-csharp vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">csharp</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">var</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> report</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> await</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> RunEvals.</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">ExecuteAsync</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    agent,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    dataset,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    evaluators</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">        new</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> EqualsGroundTruthEvaluator</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">        new</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> OutputContainsEvaluator</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Paris&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    ],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    experimentName</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;capital-smoke&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">);</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">Console.</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">WriteLine</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(report.</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">PassRate</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Output Contains&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">));</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><p>That gives you one report with case results, metric values, pass-rate helpers, and JSON output for CI artifacts.</p><h2 id="evaluator-choice" tabindex="-1">Evaluator Choice <a class="header-anchor" href="#evaluator-choice" aria-label="Permalink to &quot;Evaluator Choice&quot;">​</a></h2><p>If you are not sure which evaluator to start with, use the <a href="./evaluator-picker">Evaluator Picker</a>.</p><p>Use deterministic evaluators when you want a repeatable test:</p><ul><li>exact ground-truth match</li><li>output contains a required phrase</li><li>JSON, XML, HTML, SQL, or schema checks</li><li>tool-call and performance checks</li></ul><p>Use judge evaluators when the question is subjective:</p><ul><li>correctness</li><li>tone</li><li>refusal quality</li><li>policy fit</li><li>answer completeness</li></ul><p>Judge evaluators call another model or agent, so treat them as quality signals unless your own policy defines the threshold and review process.</p><h2 id="storage" tabindex="-1">Storage <a class="header-anchor" href="#storage" aria-label="Permalink to &quot;Storage&quot;">​</a></h2><p>Use <code>InMemoryScoreStore</code> for local runs, tests, and examples. It is not durable storage. For production score history, wire <code>IScoreStore</code> to application storage.</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("guides/evaluations/overview.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const overview = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  overview as default
};
