import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Built-In Harnesses","description":"","frontmatter":{},"headers":[],"relativePath":"guides/harnesses/overview.md","filePath":"guides/harnesses/overview.md","lastUpdated":null}');
const _sfc_main = { name: "guides/harnesses/overview.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="built-in-harnesses" tabindex="-1">Built-In Harnesses <a class="header-anchor" href="#built-in-harnesses" aria-label="Permalink to &quot;Built-In Harnesses&quot;">​</a></h1><p>Built-in harnesses are ready-made tool groups for common agent capabilities.</p><table tabindex="0"><thead><tr><th>Harness</th><th>Use it for</th><th>Status</th></tr></thead><tbody><tr><td>Coding</td><td>Workspace-aware read, search, edit, and command workflows</td><td>Use with permissions and sandboxing</td></tr><tr><td>FileSystem</td><td>Explicit filesystem operations over a configured root</td><td>Use with an explicit <code>FileSystemContext</code></td></tr><tr><td>Coding TUI</td><td>TUI renderers and controls for coding harness events</td><td>Compose into the TUI registry</td></tr><tr><td>WebSearch</td><td>Public web search through Tavily</td><td>Use with an explicit Tavily key or <code>Tavily:ApiKey</code> configuration</td></tr></tbody></table><p>Use built-in harnesses the same way you use your own harnesses: register them on <code>AgentBuilder</code>, then configure the runtime context they require.</p><h2 id="safety-defaults" tabindex="-1">Safety Defaults <a class="header-anchor" href="#safety-defaults" aria-label="Permalink to &quot;Safety Defaults&quot;">​</a></h2><p>Filesystem and coding tools can mutate files or run processes. Start with:</p><ul><li>an explicit workspace root</li><li><code>WithPermissions()</code></li><li><code>WithLocalSandbox()</code> when command execution is available</li><li>shell disabled unless the workflow truly needs it</li></ul><div class="language-csharp vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">csharp</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">var</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> agent</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> await</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> new</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> AgentBuilder</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    .</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">WithInstructions</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Stay inside the configured workspace.&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    .</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">WithPermissions</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    .</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">WithLocalSandbox</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    .</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">WithToolHarness</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">CodingToolHarness</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&gt;()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    .</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">BuildAsync</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">();</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><h2 id="recommended-reading" tabindex="-1">Recommended Reading <a class="header-anchor" href="#recommended-reading" aria-label="Permalink to &quot;Recommended Reading&quot;">​</a></h2><ul><li><a href="./coding">Coding Harness</a></li><li><a href="./filesystem">FileSystem Harness</a></li><li><a href="./coding-tui">Coding TUI</a></li><li><a href="./web-search">Web Search Harness</a></li><li><a href="./../sandboxing/overview">Sandboxing Overview</a></li><li><a href="./../middleware/permissions">Permissions</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("guides/harnesses/overview.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const overview = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  overview as default
};
